### ISSUE TITLE
Generar modelo de datos de Audiencias

### ISSUE THREAD

**Issue by pilimayora** [transparencia-argentina/audiencias#1]
Referencia de DER:
https://docs.google.com/document/d/1CBBRQ91i4TUcn4wQKjBWImB_U74sP-cjqGXaDFUaUvA/edit#heading=h.yo6a7ocbg7y9

**Comment by vmartemianov** [comment]
https://docs.google.com/document/d/15ncjmWZYmN6zJtFpHx3HTxcYsgbAR_LWzfo8PPk-PBg/edit
